### ISSUE TITLE
wifidog-wiwiz-20130917  这个编译一直报错

### ISSUE THREAD

**Issue by dl250** [wiwizcom/WiFiPortal#4]
make[6]: *** [wifidog] Error 1
make[6]: Leaving directory '/home/ubuntu/openwrt-wiwiz/lede/build_dir/target-x86_64_musl/wifidog-wiwiz-20130917/src'
Makefile:485: recipe for target 'all-recursive' failed
make[5]: *** [all-recursive] Error 1
make[5]: Leaving directory '/home/ubuntu/openwrt-wiwiz/lede/build_dir/target-x86_64_musl/wifidog-wiwiz-20130917'
Makefile:392: recipe for target 'all' failed
make[4]: *** [all] Error 2
make[4]: Leaving directory '/home/ubuntu/openwrt-wiwiz/lede/build_dir/target-x86_64_musl/wifidog-wiwiz-20130917'
Makefile:91: recipe for target '/home/ubuntu/openwrt-wiwiz/lede/build_dir/target-x86_64_musl/wifidog-wiwiz-20130917/.built' failed
make[3]: *** [/home/ubuntu/openwrt-wiwiz/lede/build_dir/target-x86_64_musl/wifidog-wiwiz-20130917/.built] Error 2
make[3]: Leaving directory '/home/ubuntu/openwrt-wiwiz/lede/package/WiFiPortal/wifidog-wiwiz'
time: package/WiFiPortal/wifidog-wiwiz/compile#10.92#1.78#13.44
    ERROR: package/WiFiPortal/wifidog-wiwiz failed to build.
package/Makefile:114: recipe for target 'package/WiFiPortal/wifidog-wiwiz/compile' failed
make[2]: *** [package/WiFiPortal/wifidog-wiwiz/compile] Error 1
make[2]: Leaving directory '/home/ubuntu/openwrt-wiwiz/lede'
package/Makefile:110: recipe for target '/home/ubuntu/openwrt-wiwiz/lede/staging_dir/target-x86_64_musl/stamp/.package_compile' failed
make[1]: *** [/home/ubuntu/openwrt-wiwiz/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/ubuntu/openwrt-wiwiz/lede'
/home/ubuntu/openwrt-wiwiz/lede/include/toplevel.mk:228: recipe for target 'world' failed

**Comment by dl250** [comment]
PKG_NAME:=wifidog-wiwiz
PKG_VERSION:=20130917
删除:=20130917就可解决，前边的字母不用删除

**Comment by wiwizcom** [comment]
日志貌似不完整。请提供完整的报错日志。
